### ISSUE TITLE
Pay dues with Paypal

### ISSUE THREAD

**Issue by misspokeycat** [exewebdev/exe#34]

**Comment by misspokeycat** [comment]
Works as of now, however not sure where it would be a good idea to add a link to the payment page.
@rzuniga64 , where do you think a good place to put the link would be?

**Comment by misspokeycat** [comment]
Also, I think it would be nice if we also had a Stripe payment gadget on the site to take payments as well - this works nice for people who want to pay by card but don't like using Paypal.

**Comment by rz1005** [comment]
Oy, now you are getting into human factors.  Here are some options:
1. this is why I originally wanted to have a right side bar on the home page, for things such as donation button, membership dues, ( a well with a description and pay button) and blog entries section. 
2. There should be an option to pay dues on the join page fer sure (with a description of its advantages). 
3. We could put a "pay dues" option in the global nav but it's already crowded. But we could add a second row as I've seen many sites using that option.  That doesn't look very clean though and how would that work on a phone since we collapse the nav bar?
4. Put a link "pay dues" button in the footer.  The footer is a nice catch all spot for things and its available from all pages.
5. Since this involves money, I think Joshua and Avery(treasurer) would want some input.

**Comment by misspokeycat** [comment]
Because a login is required to pay dues in the first place, we could make it show up in a mouse over of the users's name when they are logged in, and a dropdown could appear with 

```
My Profile
My Settings
Pay Dues (this would only appear if the user is not already marked as paid)
```

(I want to implement some site-wide preferences that are not related to contact information, such as email opt-in and public profile display for settings.)

As for the sidebar, it's still very possible - you added one in the career pages that works nice on mobile, so it's not too difficult to add one to home as well (in fact, this will probably have to be done for adding a Facebook gadget as per #17 , as adding one at the bottom would look weird IMO).  However, I don't think that's the best place for a pay dues gadget.  On the other hand, a donation link in the footer or sidebar sound like a good idea.

**Comment by rz1005** [comment]
A drop down menu on mouse over sounds ideal.  The good side is its not very in-your-face. The downside is its not very in-your-face which I think Avery would want.  I kept forgetting to pay dues for weeks and weeks because it just wasn't very convenient. As for the side bar, I still like the idea. Maybe collapse it on mouse out.  I remember you mentioning that maybe the career side bar should work like that ( you mentioned w3schools).  Yeah, the option to get the sidebar out of the way.  Like I said, nice place to put blog posts which Joshua was toying around with doing. Wordpress tends to put their archived blog posts in a sidebar. And it would handle things such as advertising important events or things we haven't thought of yet.

**Comment by misspokeycat** [comment]
I'll open up an issue for it, but it sounds like a nice front-end task for someone else to do, so I leave that to them :smiley:

**Comment by misspokeycat** [comment]
This functionality is complete, but links to the payment page need to be added to the site.  I will open a new issue so it is more clear what needs to be done.
